# NumPy

## General purpose array processing package

In [1]:
# conda install numpy

In [3]:
# Import library
import numpy as np

In [4]:
my_list = [1,2,3,4,5,6,7,8,9,10]

In [5]:
array_from_list = np.array(my_list)

In [6]:
array_from_list

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [7]:
type(array_from_list)

numpy.ndarray

In [8]:
array_from_list.shape

(10,)

In [10]:
lst_1 = [24,7,1991]
lst_2 = [24,5,1993]
lst_3 = [25,8,2019]

arr = np.array([lst_1, lst_2, lst_3])
arr

array([[  24,    7, 1991],
       [  24,    5, 1993],
       [  25,    8, 2019]])

In [11]:
arr.shape

(3, 3)

In [12]:
arr[:,:]

array([[  24,    7, 1991],
       [  24,    5, 1993],
       [  25,    8, 2019]])

In [13]:
arr[0:2,:]

array([[  24,    7, 1991],
       [  24,    5, 1993]])

In [16]:
arr[0:2,1:]

array([[   7, 1991],
       [   5, 1993]])

In [17]:
num_arr = np.arange(1,50,5)
num_arr

array([ 1,  6, 11, 16, 21, 26, 31, 36, 41, 46])

In [20]:
np.linspace(1,20,100)

array([ 1.        ,  1.19191919,  1.38383838,  1.57575758,  1.76767677,
        1.95959596,  2.15151515,  2.34343434,  2.53535354,  2.72727273,
        2.91919192,  3.11111111,  3.3030303 ,  3.49494949,  3.68686869,
        3.87878788,  4.07070707,  4.26262626,  4.45454545,  4.64646465,
        4.83838384,  5.03030303,  5.22222222,  5.41414141,  5.60606061,
        5.7979798 ,  5.98989899,  6.18181818,  6.37373737,  6.56565657,
        6.75757576,  6.94949495,  7.14141414,  7.33333333,  7.52525253,
        7.71717172,  7.90909091,  8.1010101 ,  8.29292929,  8.48484848,
        8.67676768,  8.86868687,  9.06060606,  9.25252525,  9.44444444,
        9.63636364,  9.82828283, 10.02020202, 10.21212121, 10.4040404 ,
       10.5959596 , 10.78787879, 10.97979798, 11.17171717, 11.36363636,
       11.55555556, 11.74747475, 11.93939394, 12.13131313, 12.32323232,
       12.51515152, 12.70707071, 12.8989899 , 13.09090909, 13.28282828,
       13.47474747, 13.66666667, 13.85858586, 14.05050505, 14.24

In [24]:
# copy function and broadcasting
array_from_list
arr1 = array_from_list
arr1[5:] = 500
# arr1 is reference type of array_from_list
array_from_list

array([  1,   2,   3,   4,   5, 500, 500, 500, 500, 500])

In [25]:
arr2 = array_from_list.copy()
arr2

array([  1,   2,   3,   4,   5, 500, 500, 500, 500, 500])

In [27]:
arr2[6:] = 1000
print(arr1)
print(arr2)

[  1   2   3   4   5 500 500 500 500 500]
[   1    2    3    4    5  500 1000 1000 1000 1000]


In [28]:
arr2*2

array([   2,    4,    6,    8,   10, 1000, 2000, 2000, 2000, 2000])

In [29]:
arr2/5

array([  0.2,   0.4,   0.6,   0.8,   1. , 100. , 200. , 200. , 200. ,
       200. ])

In [30]:
arr2

array([   1,    2,    3,    4,    5,  500, 1000, 1000, 1000, 1000])

In [32]:
arr2[arr2/6<2]

array([1, 2, 3, 4, 5])

In [41]:
np.arange(0,100,5).reshape(10,2)

array([[ 0,  5],
       [10, 15],
       [20, 25],
       [30, 35],
       [40, 45],
       [50, 55],
       [60, 65],
       [70, 75],
       [80, 85],
       [90, 95]])

In [44]:
np.ones((10,5), dtype=int)

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [45]:
np.random.rand(2,5)

array([[0.66754208, 0.89762125, 0.82467668, 0.19397377, 0.83198618],
       [0.46101537, 0.70003142, 0.75924709, 0.39206901, 0.34170119]])

In [46]:
np.random.randn(2,5)

array([[-0.95536522, -1.23718159,  0.71093493, -0.49737373,  0.71376181],
       [-0.79023099,  0.75040236,  0.81546027,  1.33658925,  0.84816416]])